-- ============================================================================
-- Oracle APEX - Jira Ticket Tracking System
-- Database Schema for Autonomous Database (ADBS)
-- ============================================================================

-- Drop existing tables if they exist (for clean reinstall)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE jira_ticket_history CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE jira_tickets CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE team_members CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE teams CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE jira_tickets_seq';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE teams_seq';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE team_members_seq';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================================
-- Create Teams Table
-- ============================================================================
CREATE TABLE teams (
    team_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name           VARCHAR2(100) NOT NULL UNIQUE,
    team_description    VARCHAR2(500),
    is_active           VARCHAR2(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    created_by          VARCHAR2(100) DEFAULT USER,
    created_date        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_by          VARCHAR2(100),
    updated_date        TIMESTAMP
);

-- ============================================================================
-- Create Team Members Table (Role-based access)
-- ============================================================================
CREATE TABLE team_members (
    member_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id             NUMBER NOT NULL,
    username            VARCHAR2(100) NOT NULL,
    email               VARCHAR2(200),
    member_role         VARCHAR2(50) NOT NULL CHECK (member_role IN ('ADMIN', 'MANAGER', 'EDITOR', 'VIEWER')),
    is_active           VARCHAR2(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    created_by          VARCHAR2(100) DEFAULT USER,
    created_date        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_by          VARCHAR2(100),
    updated_date        TIMESTAMP,
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id) REFERENCES teams(team_id) ON DELETE CASCADE,
    CONSTRAINT uk_team_member UNIQUE (team_id, username)
);

-- ============================================================================
-- Create Jira Tickets Table
-- ============================================================================
CREATE TABLE jira_tickets (
    ticket_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id             NUMBER NOT NULL,
    jira_key            VARCHAR2(50) NOT NULL,
    jira_id             VARCHAR2(50),
    ticket_summary      VARCHAR2(500) NOT NULL,
    ticket_description  CLOB,
    ticket_type         VARCHAR2(50) CHECK (ticket_type IN ('Story', 'Bug', 'Task', 'Epic', 'Sub-task', 'Improvement')),
    priority            VARCHAR2(20) CHECK (priority IN ('Critical', 'High', 'Medium', 'Low', 'Trivial')),
    status              VARCHAR2(50) NOT NULL,
    assignee            VARCHAR2(100),
    reporter            VARCHAR2(100),
    sprint              VARCHAR2(100),
    story_points        NUMBER(5,1),
    original_estimate   NUMBER(10,2), -- in hours
    time_spent          NUMBER(10,2), -- in hours
    remaining_estimate  NUMBER(10,2), -- in hours
    resolution          VARCHAR2(50),
    labels              VARCHAR2(500), -- comma-separated labels
    components          VARCHAR2(500), -- comma-separated components
    fix_version         VARCHAR2(100),
    due_date            DATE,
    resolved_date       TIMESTAMP,
    week_number         NUMBER(2),
    week_year           NUMBER(4),
    week_start_date     DATE,
    week_end_date       DATE,
    is_active           VARCHAR2(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    created_by          VARCHAR2(100) DEFAULT USER,
    created_date        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_by          VARCHAR2(100),
    updated_date        TIMESTAMP,
    CONSTRAINT fk_tickets_team FOREIGN KEY (team_id) REFERENCES teams(team_id),
    CONSTRAINT uk_jira_key UNIQUE (jira_key)
);

-- ============================================================================
-- Create Jira Ticket History Table (for weekly snapshots)
-- ============================================================================
CREATE TABLE jira_ticket_history (
    history_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id           NUMBER NOT NULL,
    jira_key            VARCHAR2(50) NOT NULL,
    status              VARCHAR2(50) NOT NULL,
    assignee            VARCHAR2(100),
    sprint              VARCHAR2(100),
    story_points        NUMBER(5,1),
    time_spent          NUMBER(10,2),
    remaining_estimate  NUMBER(10,2),
    week_number         NUMBER(2) NOT NULL,
    week_year           NUMBER(4) NOT NULL,
    week_start_date     DATE NOT NULL,
    week_end_date       DATE NOT NULL,
    snapshot_date       TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by          VARCHAR2(100) DEFAULT USER,
    CONSTRAINT fk_history_ticket FOREIGN KEY (ticket_id) REFERENCES jira_tickets(ticket_id) ON DELETE CASCADE
);

-- ============================================================================
-- Create Indexes for Performance
-- ============================================================================
CREATE INDEX idx_tickets_team ON jira_tickets(team_id);
CREATE INDEX idx_tickets_status ON jira_tickets(status);
CREATE INDEX idx_tickets_week ON jira_tickets(week_number, week_year);
CREATE INDEX idx_tickets_assignee ON jira_tickets(assignee);
CREATE INDEX idx_history_ticket ON jira_ticket_history(ticket_id);
CREATE INDEX idx_history_week ON jira_ticket_history(week_number, week_year);
CREATE INDEX idx_team_members_user ON team_members(username);
CREATE INDEX idx_team_members_team ON team_members(team_id);

-- ============================================================================
-- Insert Sample Data
-- ============================================================================

-- Sample Teams
INSERT INTO teams (team_name, team_description) VALUES ('Development Team', 'Core development team');
INSERT INTO teams (team_name, team_description) VALUES ('QA Team', 'Quality Assurance team');
INSERT INTO teams (team_name, team_description) VALUES ('DevOps Team', 'DevOps and Infrastructure team');

-- Sample Team Members with different roles
INSERT INTO team_members (team_id, username, email, member_role) 
VALUES (1, 'ADMIN', 'admin@company.com', 'ADMIN');

INSERT INTO team_members (team_id, username, email, member_role) 
VALUES (1, 'DEV_MANAGER', 'devmanager@company.com', 'MANAGER');

INSERT INTO team_members (team_id, username, email, member_role) 
VALUES (1, 'DEVELOPER1', 'dev1@company.com', 'EDITOR');

INSERT INTO team_members (team_id, username, email, member_role) 
VALUES (2, 'QA_MANAGER', 'qamanager@company.com', 'MANAGER');

INSERT INTO team_members (team_id, username, email, member_role) 
VALUES (2, 'TESTER1', 'tester1@company.com', 'EDITOR');

-- Sample Jira Tickets
INSERT INTO jira_tickets (
    team_id, jira_key, jira_id, ticket_summary, ticket_description, 
    ticket_type, priority, status, assignee, reporter,
    sprint, story_points, week_number, week_year, week_start_date, week_end_date
) VALUES (
    1, 'DEV-101', 'JIRA-101', 'Implement user authentication', 
    'Add OAuth2 authentication to the application',
    'Story', 'High', 'In Progress', 'DEVELOPER1', 'DEV_MANAGER',
    'Sprint 23', 8, 6, 2026, DATE '2026-02-02', DATE '2026-02-08'
);

INSERT INTO jira_tickets (
    team_id, jira_key, jira_id, ticket_summary, ticket_description, 
    ticket_type, priority, status, assignee, reporter,
    sprint, story_points, week_number, week_year, week_start_date, week_end_date
) VALUES (
    1, 'DEV-102', 'JIRA-102', 'Fix database connection pooling', 
    'Optimize database connection pool settings',
    'Bug', 'Critical', 'To Do', 'DEVELOPER1', 'DEV_MANAGER',
    'Sprint 23', 5, 6, 2026, DATE '2026-02-02', DATE '2026-02-08'
);

INSERT INTO jira_tickets (
    team_id, jira_key, jira_id, ticket_summary, ticket_description, 
    ticket_type, priority, status, assignee, reporter,
    sprint, story_points, week_number, week_year, week_start_date, week_end_date
) VALUES (
    2, 'QA-201', 'JIRA-201', 'Create automated test suite', 
    'Develop comprehensive automated tests for user module',
    'Task', 'Medium', 'In Progress', 'TESTER1', 'QA_MANAGER',
    'Sprint 23', 13, 6, 2026, DATE '2026-02-02', DATE '2026-02-08'
);

COMMIT;

-- ============================================================================
-- Success Message
-- ============================================================================
BEGIN
    DBMS_OUTPUT.PUT_LINE('Database schema created successfully!');
    DBMS_OUTPUT.PUT_LINE('Tables created: teams, team_members, jira_tickets, jira_ticket_history');
    DBMS_OUTPUT.PUT_LINE('Sample data inserted.');
END;
/
